apiVersion: v1
kind: Service
metadata:
  name: es-service
  labels:
    service: elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    service: elasticsearch
  type: LoadBalancer