# service.yml
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  clusterIP: None
  ports:
    - port: 9300
      name: transport
  selector:
    service: elasticsearch