apiVersion: v1
kind: Pod
metadata:
   name: hostpath
spec:
   containers:
      - name: redis-con
        image: redis
        volumeMounts:
             - mountPath: /tmp/test
               name: vol
   volumes:
      - name: vol
        hostPath:
            path: /tmp/test