apiVersion: v1
kind: Pod
metadata:
    name: emptydir
spec:
    containers:
      - name: nginx-con
        image: nginx
        volumeMounts:
            - name: vol
              mountPath: /tmp/test
    volumes:
      - name: vol
        emptyDir: {}