# nginx-pv-2.yml
apiVersion: v1
kind: Pod
metadata:
  name: pv-pod-2
spec:
  containers:
    - name: nginx-2
      image: nginx:1.18
      volumeMounts:
        - mountPath: /test-pd
          name: test-volume-2

  volumes:
    - name: test-volume-2
      persistentVolumeClaim:
        claimName: claim-2