---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
        name: alpine-cronjob
spec:
        schedule: "*/1 * * * *"
        successfulJobsHistoryLimit: 5
        jobTemplate:
                spec:
                        template:
                                spec:
                                        containers:
                                                - name: alpine
                                                  image: alpine
                                                  args:
                                                          - /bin/ash
                                                          - -c
                                                          - date;echo hello
                                        restartPolicy: OnFailure

