---
apiVersion: v1
kind: Pod
metadata:
        name: demo-init
        labels:
                demo: init
spec:
        containers:
                - name: nginx
                  image: nginx
                  command:
                          - "/bin/sh"
                          - "-c"
                          - "echo hello main"

        initContainers:
                - name: firstinit
                  image: busybox
                  command:
                          - "/bin/sh"
                          - "-c"
                          - "echo starting first service"

                - name: secondinit
                  image: busybox
                  command:
                          - "/bin/sh"
                          - "-c"
                          - "echo starting second service; sleep 10"
        

                

