---
apiVersion: v1
kind: ReplicationController
metadata:
        name: nginx-rc
spec:
        replicas: 3
        selector:
                app: nginx
        template:
                metadata:
                        name: nginx-pod-1
                        labels:
                                app: nginx
                                tier: dev
                spec:
                        containers:
                                - name: nginx
                                  image: nginx
                                  ports:
                                          - containerPort: 80  
