apiVersion: v1
kind: Pod
metadata:
        name: hello-pod
spec:
        containers:
                - name: hello-ctr
                  image: alpine
                  ports:
                          - containerPort: 8080
