---
apiVersion: v1
kind: Pod
metadata:
        name: side-car
        labels:
                app: nginx

spec:
        containers:
                - name: nginx
                  image: nginx
                
                - name: sidecar
                  image: alpine
                  command: ["/bin/ash"]
                  args: ["-c","echo hello world > /file.txt; sleep 3600"]



