apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gce
spec:
  capacity:
    storage: 15Gi
  storageClassName: slow
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: my-disk
    fsType: ext4