apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: traefik
spec:
  commonName: traefik.himanshuchaudhary.tech
  secretName: traefiksecret
  dnsNames:
    - traefik.himanshuchaudhary.tech
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer