apiVersion: v1
kind: Pod
metadata:
  name: test-pvc
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: mypvc
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: storage